/*	-----------------------------------------------------------------------------------------------------------------------------------------------------
		- Name:					ScoreValueText.h
		- Description:			Scores generated by the player for killing enemy objects are displayed on screen and move towards the player
		- Information:

		- Log:
			2017/03/21			Moved additional render functionality from Game class
			2017/02/10			Added functionality so the scores displayed on screen move to player who scored them (Changed from moving to players score)
			2017/02/09			Added score class ScoreValueText.h for displaying values of scores for destroying objects
			2017/02/06			Added managePlayerScores() function to handle players score to Game class
			2017/01/31			Added points value messages for each player
								Added vector list of game objects to display the scores for each object killed
------------------------------------------------------------------------------------------------------------------------------------------------------- */

#ifndef SCORE_VALUE_H
#define SCORE_VALUE_H

#include "GameObject.h"

class ScoreValueText : public GameObject {
public:
	ScoreValueText(int x, int y, int score, int player);
	~ScoreValueText();

	virtual void move(int x, int y);	// Tracker movement, scores move towards players who earned the points

	virtual void destroy() {};

	/* 
		2017/03/21 Updated render function with different alpha values for score for kills indicator text
	*/
	virtual void render() {
		//std::cout << "Test" << std::endl;

		if (getSubType() == PLAYER1_SCORE)
			m_Texture.setAlpha(120);
		else if (getSubType() == PLAYER2_SCORE)
			m_Texture.setAlpha(100);

		GameObject::render(m_Texture);
	}

	//Texture m_Texture;	// 2017/03/21
};

#endif